### ISSUE TITLE
initialize_icons not adding resource path when APP_ID or BASE_RESOURCE_PATH is set

### ISSUE THREAD

**Issue by Frajul** [Relm4/icons#18]
Hi there, 
in the icons.toml file, if I set either app_id or base_resource_path, the icons are not displayed by gtk.
I looked at your code and found that initialize_icons does not call `theme.add_resource_path` if any of these variables are set.
Is this behaviour on purpose?

When I run

    gtk::init().unwrap();
    
    let display = gdk::Display::default().unwrap();
    let theme = gtk::IconTheme::for_display(&display);
    theme.add_resource_path("/org/gtkrs/icons/");
    theme.add_resource_path("/org/gtkrs/icons/scalable/actions/");

in my code after invoking your initialize_icons, the icons are found and correctly displayed.
So what I would expect your initialize_icons function to be is:

    pub fn initialize_icons() {
        gio::resources_register_include!("resources.gresource").unwrap();
    
        gtk::init().unwrap();
    
        let display = gdk::Display::default().unwrap();
        let theme = gtk::IconTheme::for_display(&display);
    
        if icon_names::APP_ID.is_empty() && icon_names::BASE_RESOURCE_PATH.is_empty() {
            theme.add_resource_path("/org/gtkrs/icons/");
            theme.add_resource_path("/org/gtkrs/icons/scalable/actions/");
        } else if !icon_names::BASE_RESOURCE_PATH.is_empty() {
            let path = format!("{}icons/scalable/actions/", icon_names::BASE_RESOURCE_PATH);
            theme.add_resource_path(&path);
        } else {
            let path = format!(
                "/{}/icons/scalable/actions/",
                icon_names::BASE_RESOURCE_PATH.replace('.', "/")
            );
            theme.add_resource_path(&path);
        }
    }
  

So does that part of the code need to be changed or did I not understand the usage of the icons.toml config file correctly?

**Comment by AaronErhardt** [comment]
>  Is this behaviour on purpose?

It kinda is, but I forgot that Relm4 does not call `set_resource_base_path` for you automatically (I think I wanted to add that at some point). I'm planning to replace relm4-icons soon with a better solution though, so I'm not eager to fix this, especially since this can be avoided by either not using the resource base path or app ID or setting the resource base path manually in your app.

**Comment by Frajul** [comment]
Ok. Thank you for your quick answer :)
