### ISSUE TITLE
Instructions for updating icons are incomplete

### ISSUE THREAD

**Issue by nazar-pc** [Relm4/icons#23]
```
> cargo run
thread 'main' panicked at update_icons/src/icon_list.rs:22:65:
called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }
```

Instructions on updating submodules are missing, I don't use them often and have no idea how to bypass `update = none`, am I supposed to edit the file?

Also having both `main.rs` and `bin/update_icons.rs` is equally confusing.

**Comment by AaronErhardt** [comment]
This does the trick:

```sh
git submodule update --remote --checkout
```

**Comment by nazar-pc** [comment]
Yes, that works. Consider adding to readme :slightly_smiling_face:
